// Compact on-disk encoding for per-draw history.
//
// WHY THIS EXISTS
//
// Cloudflare Pages caps a Functions bundle at 25 MiB. Every game page runs on
// the edge runtime, and next-on-pages inlines the whole module graph into one
// worker — including dynamic `import()`, because Workers cannot load modules at
// runtime. So the lazy per-game import in lib/draws.ts, which does keep these
// files out of a Node/Vercel route bundle, does NOT help here: all of lib/data
// lands in the worker regardless.
//
// Stored as plain `Draw` objects that was 27.8 MB of draw history against 2.0 MB
// of aggregates, producing a 31.9 MiB bundle and a hard deploy failure:
//
//   Generated Pages Functions bundle size (33470547) is over the limit of 25.0 MiB
//
// The waste is pure repetition. Every draw serialised as
//
//   {"game":"pick3","date":"1980-09-02","stream":"evening","digits":[2,5,5],"index":0}
//
// — 86 bytes, of which the game name, the spelled-out stream and a positional
// index are identical or derivable across all 25,679 rows of that file. Encoded
// as one string per draw,
//
//   "1980-09-02|e|255"
//
// the same row costs ~19 bytes: roughly a 4.5x reduction, taking the picks from
// ~27 MB to ~6 MB and the bundle comfortably back under the limit.
//
// Ball games (Powerball, Mega Millions) are left in the original object form on
// purpose — together they are only ~0.7 MB, so compacting them would add risk
// for no meaningful saving. `decodeDrawFile` accepts either shape.
//
// This is a build-artifact format, not a public API: lib/data/*.json is
// regenerated by `npm run ingest` on every build, so there is nothing to
// migrate. Bump VERSION if the row grammar changes.

import type { Draw, Stream } from "./types";

export const DRAW_FILE_VERSION = 2;

/** Single-char stream codes. "other" is the catch-all for untagged rows. */
const STREAM_TO_CODE: Record<Stream, string> = {
  morning: "m",
  midday: "d",
  evening: "e",
  night: "n",
  other: "o",
};
const CODE_TO_STREAM: Record<string, Stream> = {
  m: "morning",
  d: "midday",
  e: "evening",
  n: "night",
  o: "other",
};

export type EncodedPickFile = {
  game: string;
  v: number;
  /** "pick3" | "pick4" — restored onto every decoded Draw. */
  kind: "pick3" | "pick4";
  /** One row per draw: `YYYY-MM-DD|<streamCode>|<digits>`. */
  rows: string[];
  report: unknown;
};

/** Legacy / ball-game shape: draws stored as full objects. */
type PlainFile = { game: string; draws: Draw[]; report: unknown };

/** `Draw[]` → compact rows. Digits are concatenated, so 0-9 only. */
export function encodePickDraws(draws: Draw[]): string[] {
  return draws.map((d) => {
    const code = STREAM_TO_CODE[(d.stream ?? "other") as Stream] ?? "o";
    return `${d.date}|${code}|${(d.digits ?? []).join("")}`;
  });
}

/**
 * Read either encoding back into `Draw[]`.
 *
 * `index` is reassigned from array position rather than stored — it was always
 * just the ordinal of the (already chronologically sorted) row.
 */
export function decodeDrawFile(file: unknown): Draw[] {
  const f = file as Partial<EncodedPickFile> & Partial<PlainFile>;

  if (Array.isArray(f.rows) && f.kind) {
    const kind = f.kind;
    return f.rows.map((row, index) => {
      const bar1 = row.indexOf("|");
      const bar2 = row.indexOf("|", bar1 + 1);
      const date = row.slice(0, bar1);
      const stream = CODE_TO_STREAM[row.slice(bar1 + 1, bar2)] ?? "other";
      const digitsStr = row.slice(bar2 + 1);
      const digits: number[] = new Array(digitsStr.length);
      for (let i = 0; i < digitsStr.length; i++) digits[i] = digitsStr.charCodeAt(i) - 48;
      return { game: kind, date, stream, digits, index };
    });
  }

  // Ball games and any pre-v2 file.
  return (f.draws ?? []) as Draw[];
}
